obj-$(CONFIG_INPUT_SEC_SECURE_TOUCH)	+= sec_secure_touch.o
obj-$(CONFIG_INPUT_SEC_INPUT) += sec_common_fn.o sec_cmd.o
obj-$(CONFIG_INPUT_SEC_NOTIFIER) += sec_input_notifier.o

obj-$(CONFIG_TOUCHSCREEN_SLSI)	+= slsi/

ccflags-y += -Wformat
